JY-44: 코드 리팩토링을 진행한다
DONOTINTO/Login_SpotifyUI pull request #18
Opened 2023-04-14 10:01 UTC by DONOTINTO

- 카드번호 : [JY-44](https://keentutoring.atlassian.net/browse/JY-44)
  - 반복되는 코드를 메소드로 묶어 코드 리팩토링을 진행한다.

2023-04-14 10:07 UTC, keenkim1202 requested changes

2023-04-14 10:07 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/View/SignUpView.swift
> +        labelInit(identificationLabel, title: "아이디 또는 이메일 주소", textColor: .white, font: ProjFont.metro25!)
옵셔널 언래핑은 ProjFont 내부에서 미리 해주세요!
(여기에서는 ! 가 보이지 않도록)

2023-04-15 05:00 UTC, DONOTINTO commented on Login_SpotifyUI/Login_SpotifyUI/View/SignUpView.swift
> +        labelInit(identificationLabel, title: "아이디 또는 이메일 주소", textColor: .white, font: ProjFont.metro25!)
@keenkim1202 수정완료헀습니다!

2023-04-15 05:05 UTC, keenkim1202 approved these changes

2023-04-15 05:05 UTC, merged