JY-3 : DB를 적용한다.
DONOTINTO/Login_SpotifyUI pull request #24
Opened 2023-04-17 12:14 UTC by DONOTINTO

- 카드번호 : [JY-3](https://keentutoring.atlassian.net/browse/JY-3)
  - static 키워드를 사용하여 배열을 만들어 DB 처럼 사용한다.

2023-04-17 12:31 UTC, keenkim1202 requested changes
@DONOTINTO 수정부탁드립니다~!

2023-04-17 12:31 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/SignUpViewController.swift
> +    func makeRandomKey() -> Int {
키값은 변경될 일이 없는 고유한 값입니다.
여기에서 키를 생성하는 것 보다 모델에서 아예 초기값으로 키값읕 주면 어떨까요?

2023-04-17 12:31 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Model/RegisterManager.swift
> +        for idx in 0 ..< count {
인덱스로 접근하기보다 forEach문이나 고차함수를 활용하는 방향으로 수정해보면 좋을 듯합니다.
혹은 코멘트에 메모해두고 향후 리팩토링 시 수정하셔도됩니다.

2023-04-17 14:33 UTC, keenkim1202 requested changes

2023-04-17 14:33 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/SignUpViewController.swift
> +        let key = Int.random(in: 1 ... 99999)
```suggestion
        let key = Int.random(in: 1...99999)
```

2023-04-17 14:33 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Model/RegisterManager.swift
> +        for idx in 0 ..< count {
추천 코드는 아래와 같습니다.
```suggestion
        if let index = registerList.firstIndex(where: { $0.keyNumber == key }) {
            registerList[index].password = password
        }
```

2023-04-18 14:00 UTC, DONOTINTO commented on Login_SpotifyUI/Login_SpotifyUI/Controller/SignUpViewController.swift
> +    func makeRandomKey() -> Int {
현재는 범위 안에서 랜덤한 숫자를 생성하고 있는데,
초기값으로 키를 랜덤하게 줄 때 중복처리가 고민입니다

2023-04-18 14:09 UTC, DONOTINTO commented
@keenkim1202 수정 완료했습니다!

2023-04-18 14:11 UTC, keenkim1202 approved these changes
수고하셨습니다!

2023-04-18 14:11 UTC, merged