JY-77 : 로그인 - 로그인 실패 경우를 대처한다.
DONOTINTO/Login_SpotifyUI pull request #32
Opened 2023-04-22 01:19 UTC by DONOTINTO

- 카드번호 : [JY-77](https://keentutoring.atlassian.net/browse/JY-77)
  - 회원가입한 적 없는 경우
  - 아이디 혹은 비밀번호가 일치하지 않는 경우

2023-04-23 10:28 UTC, keenkim1202 requested changes

2023-04-23 10:28 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/LoginViewController.swift
> +        if registerInfo!.password == password { return true }
first가 존재하지 않을 가능성을 고려하여 강제 언래핑보다는 `if let`, `guard let`을 사용하면 좋을 것 같습니다~!

2023-04-24 11:23 UTC, DONOTINTO commented
@keenkim1202 수정완료했습니다!

2023-04-24 14:20 UTC, keenkim1202 approved these changes

2023-04-24 14:20 UTC, merged