JY-89 : 홈 화면을 구현한다.
DONOTINTO/Login_SpotifyUI pull request #33
Opened 2023-04-24 14:19 UTC by DONOTINTO

- 카드번호 : [JY-89](https://keentutoring.atlassian.net/browse/JY-89)
  - 큰 틀(위치, 요소)만 가져가고 디테일한 UI 인은 자유롭게 수정해도 됩니다.
  - 가장 상위에는 UIScrollView를 추가하여 스크롤이 가능하도록 구현해주세요.
  - 마이 플레이 리스트는 고정된 높이 값을 갖습니다. (height: 700)
  - 향후, 로그아웃 버튼은 NavigationBar로 이동시킬 예정입니다.
  - 향후, 정보 수정 화면에 회원탈퇴 버튼을 이동시킬 예정입니다.
  - 위의 두 버튼(로그아웃, 회원탈퇴)의 위치를 이동 시킨 후 고정 높이 값을 없앨 예정입니다.

2023-04-24 15:42 UTC, keenkim1202 requested changes
항상 아래 사항을 체크 후 PR을 생성해주세요~!

1) 컨벤션이 일관되게 적용되어있는지
2) 불필요한 공백, tab 간격, 빈줄은 정리했는지

2023-04-24 15:42 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +
모든 ViewController의 컨벤션은 일관성이 있어야 합니다.
빈줄을 제거해주세요!

2023-04-24 15:42 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +
모든 ViewController의 컨벤션은 일관성이 있어야 합니다.
`EntryVC`의 경우 이 위치에 한줄 띄기가 안되어있습니다.
모든 ViewController에 대해 `super.viewDidLoad()` 다음에 한 줄을 띄어주세요!

2023-04-24 15:42 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/SignUpViewController.swift
> +        guard Int(phone) != nil else {
이 경우는 `if` 문이 적절해보입니다.
`phone`을 `Int` 타입으로 캐스팅한 결과가 `nil` 인지 비교하는 조건문이므로 
early exit을 위한 `guard`문을 사용할 필요가 없습니다.

2023-04-24 15:42 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Model/RegisterManager.swift
> +
빈줄을 제거해주세요~!
(켠벤션 일관성 유지하기)

2023-04-24 15:42 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/View/EntryView.swift
> +    let testButton = UIButton()
테스트 버튼을 만든 것은 좋습니다!
하지만 테스트 버튼을 눌렀을 때 이동한 화면에서 벗어나는 버튼도 필요합니다.

1회성으로 테스트 버튼을 누르고 그 화면을 벗어날 수 없다면 매번 앱을 재실행해야 하므로 테스트가 효율적이지 않습니다.

2023-04-24 15:42 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/View/HomeScrollView.swift
> +
빈줄을 제거해주세요
(컨벤션의 일관성 유지)

2023-04-24 15:42 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/View/ProfileView.swift
> +
빈줄은 지워주세요
(컨벤션 일관성 유지)

2023-04-24 15:42 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/View/ProfileView.swift
> +
`LoginView` 도 같은 부분에서 한 줄 띄어주세요

2023-04-24 15:42 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/View/ProfileView.swift
> +
`SignUpVIew` 도 마찬가지 입니다!

2023-04-26 12:39 UTC, DONOTINTO commented
@keenkim1202 수정 완료했습니다!

2023-04-26 16:08 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/View/EntryView.swift
> +    let testButton = UIButton()
@DONOTINTO 
테스트 화면에서 벗어날 수 있도록 화면을 닫는 버튼을 추가해주세요~!

2023-04-27 14:50 UTC, DONOTINTO commented on Login_SpotifyUI/Login_SpotifyUI/View/EntryView.swift
> +    let testButton = UIButton()
@keenkim1202 로그아웃버튼에 해당 기능을 추가해두었습니다!

2023-04-29 10:41 UTC, DONOTINTO commented on Login_SpotifyUI/Login_SpotifyUI/View/EntryView.swift
> +    let testButton = UIButton()
@keenkim1202 네! 밑으로 내려서 로그아웃 버튼을 클릭하면 됩니다!

2023-04-29 16:31 UTC, keenkim1202 approved these changes

2023-04-29 16:31 UTC, merged