JY-70 : 홈 화면의 기능을 모두 구현한다.
DONOTINTO/Login_SpotifyUI pull request #35
Opened 2023-04-28 13:33 UTC by DONOTINTO

- 카드번호: [JY-70](https://keentutoring.atlassian.net/browse/JY-70)

2023-04-28 14:48 UTC, keenkim1202 requested changes
@DONOTINTO 확인 후 수정부탁드립니다~

2023-04-28 14:48 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/SignUpViewController.swift
> +        guard let nickName = signUpView.nickNameTextField.text else { return }
nickname은 단어 그 자체로 별칭이라는 뜻이므로 중간에 camelcase로 표시할 필요가 없습니다~!
```suggestion
        guard let nickname = signUpView.nickNameTextField.text else { return }
```

2023-04-28 14:48 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Model/Register.swift
> +    var nickName: String
```suggestion
    var nickname: String
```

2023-04-28 14:48 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/View/ProfileView.swift
> +        profileImage.image = UIImage(systemName: "pencil")
이미지의 색상이 기본색상(파란색)입니다.
앱의 메인 색상으로 맞춰주세요~!

<img width=250 src="https://user-images.githubusercontent.com/59866819/235177673-ef90fb47-f9ee-4719-8cab-4fdaf4b32e50.png">

2023-04-28 14:48 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/View/SignUpView.swift
> +    let nickNameLabel = UILabel()
```suggestion
    let nicknameLabel = UILabel()
```

아래 textField도 마찬가지 입니다

2023-04-28 14:48 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/View/SignUpView.swift
>              $0.top.equalTo(passwordLabel.snp.bottom).offset(8)
모든 textField에서 비밀번호 입력시, 첫글자가 자동 대문자가 되지 않도록 해주세요~
<img width=250 src="https://user-images.githubusercontent.com/59866819/235178241-a137d63f-193b-4c59-afa9-e6e5619ad109.png"> <img width=250 src="https://user-images.githubusercontent.com/59866819/235178250-8a04d8fb-8dc9-4f10-a1f4-8898f7f36d5e.png">

2023-04-28 14:48 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/SignUpViewController.swift
> +        let register = Register(identification: identification,nickName: nickName , password: password, phone: phone)
```suggestion
        let register = Register(identification: identification, nickName: nickName, password: password, phone: phone)
```

2023-04-28 14:48 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/SignUpViewController.swift
> +        let duplicationNickName = RegisterManager.shared.registerList.filter { $0.nickName == nickName }
이 함수는 `nicknameTextField`에 입력된 것과 같은 nickname이 등록된 적이 있는지 체크하기 위해 작성한 것으로 보여집니다.

1) `duplication` 의 뜻은 "복사, 복제" 이므로 네이밍이 적절하지 않아보입니다. 더 좋은 네이밍은 뭐가 있을까요?
2) 기존에 등록된 적 있는지 체크하는데, `filter`를 사용하는 것이 아닌 더 좋은 방법이 없을까요?

2023-04-29 16:24 UTC, DONOTINTO commented
@keenkim1202 수정완료했습니다!

2023-04-29 16:37 UTC, keenkim1202 approved these changes
좋습니다 !

2023-04-29 16:54 UTC, merged