JY-104 : PlayList 모델을 생성 및 화면에 정보를 보여준다
DONOTINTO/Login_SpotifyUI pull request #36
Opened 2023-04-28 13:34 UTC by DONOTINTO

- 카드번호 : [JY-104](https://keentutoring.atlassian.net/browse/JY-104)
  - 노래 제목, 아티스트, 좋아요 체크 여부를 담은 PlayList 모델을 생성하여 화면에 데이터를 나타낸다.

2023-04-28 14:56 UTC, keenkim1202 requested changes
@DONOTINTO 수정 부탁드립니다~

2023-04-28 14:56 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +            let likeList = register.playList?.list.filter { $0.like == true }
bool타입의 경우 == true 를 작성할 필요 없습니다.
(false의 경우도 마찬가지 입니다.)
```suggestion
            let likeList = register.playList?.list.filter { $0.like }
```

----

ex1) true인지 판별하고 싶은 경우
```swift
var flag = true

if flag {
   // do something
}
```

ex2) false인지 판별하고 싶은 경우
```swift
var flag = true

if !flag {
   // do something
}
```

2023-04-28 14:56 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +            let likeList = register.playList?.list.filter { $0.like == true }
`register.playList` 가 옵셔널 값이므로 안전하게 언래핑 해주세요~! 
아래 `likeList`도 마찬가지 입니다.

2023-04-28 14:56 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/View/PlayListTableViewCell.swift
> +        if music.like == true {
```suggestion
        if music.like {
```

2023-04-28 14:56 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Model/Music.swift
> +    var like: Bool = true
bool 타입의 변수명은 애플에서 제공하는 swift 컨벤션을 따르면 `is~`, `has~` 와 같이 네이밍하는 것을 추천하고 있습니다.
대표적인 예시로는 `isEmpty`가 있습니다.

이 경우에도 `isLike` 와 같은 네이밍을 주면, 모델을 보지 않고도 누구나 bool타입 값일 것임을 예측할 수 있습니다.

2023-04-29 16:32 UTC, DONOTINTO commented
@keenkim1202 수정완료했습니다!

2023-04-29 16:34 UTC, keenkim1202 approved these changes

2023-04-29 16:42 UTC, merged