JY-115 : UX/UI 개선 및 코드 수정
DONOTINTO/Login_SpotifyUI pull request #44
Opened 2023-05-11 14:33 UTC by DONOTINTO

- 카드번호 : [JY-115](https://keentutoring.atlassian.net/browse/JY-115)
  - 로그인 비밀번호 숨김 시 미일치 오류 수정
  - HomeVC TableCell 간격 조정
  - HomeVC TableView 높이 조정

2023-05-11 15:21 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +        guard let heightForRow = self.heightForRow else { return }
`guard`문이 위에 있으면 아래의 button action을 추가하는 `addTarget`이나 `updateProfileView()` 가 작동하지 않을 수 있습니다.

이 위치에 작성하고자 한다면 `if let` 구문을 사용,
`guard`문을 사용하고자 한다면 함수 제일 하단으로 코드를 옮겨주세요~

2023-05-11 15:23 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +        if let register = self.register {
이 경우, `else` 구문을 활용하는 일이 없고, `register`가 존재하지 않으면 함수를 종료하므로 `gaurd`문을 사용하는 것이 더 적절해보입니다.

`guard`문을 사용함으로써 early exit 효과를 볼 수 있고, bracket의 뎁스(depth)가 줄어들어 가독성이 올라갑니다.

2023-05-11 15:24 UTC, keenkim1202 commented
@DONOTINTO 
코멘트 반영하고 수정 & conflict 해결해주세요~

2023-05-13 15:56 UTC, keenkim1202 requested changes

2023-05-13 15:56 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +        let cb: () -> () = {
1) 네이밍
cb 라는 단어만 보고 다른 개발자가 어떤 역할을 하는지 유추할 수 있을까요?
네이밍만 보고도 어떤 역할을 하는지 알아볼 수 있도록 이름을 정해주는 것이 중요합니다.

2) 컨밴션
closure의 경우, 일반적인 표기 방법은 `() -> Void` 로 표기합니다.

3) `cb`라는 상수를 만들어 사용한 이유
`updateProfileView()`함수 하나만 호출하는 클로저를 만든 이유가 무엇인가요?

2023-05-13 15:56 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/PlayListTableViewCell.swift
> +            let view = UIView(frame: CGRect(x: 0, y: 0, width: 0, height: 0))
뷰의 크기와 위치를 0으로 초기화해준 이유는 무엇인가요?

2023-05-13 15:56 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/PlayListTableViewCell.swift
> +    override func setHighlighted(_ highlighted: Bool, animated: Bool) {
이 함수가 필요한 이유가 무엇인가요??

2023-05-15 13:53 UTC, DONOTINTO commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +        let cb: () -> () = {
@keenkim1202 
1. callback으로 정정하겠습니다!
2. 넵!
3. cell에서 '하트'를 클릭하면 profileView에 있는 데이터를 업데이트해줘야하는데,
cell에서 HomeVC에 있는 HomeView에 ProfileView를 업데이트해줄 방법이 마땅히 생각나지 않아서 해당 클로저를 cell에서 callback 변수에 저장해서 호출했습니다.

2023-05-15 14:00 UTC, DONOTINTO commented on Login_SpotifyUI/Login_SpotifyUI/Controller/PlayListTableViewCell.swift
> +    override func setHighlighted(_ highlighted: Bool, animated: Bool) {
@keenkim1202 
cell 별 spacing을 주기위해서 Cell에 UIView를 만들고 그 안에 텍스트같은 인스턴스들을 올렸습니다.
그 결과 Cell을 클릭했을 때 Cell 자체 contentView가 하이라이트 되어 gray색이 나와서 하이라이트 색상을 clear로 바꿔주었습니다.

2023-05-16 06:11 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +        let cb: () -> () = {
@DONOTINTO 
넵 확인했습니다 :) 
향후에 더 좋은 방법이 있는지 같이 체크해보고 리팩토링하도록 해요~!

2023-05-16 06:13 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/PlayListTableViewCell.swift
> +    override func setHighlighted(_ highlighted: Bool, animated: Bool) {
@DONOTINTO 
`cell.selectionStyle = .none`
를 사용하면 해당 이슈를 해결할 수 있습니다~!
함수를 `override`하지 않고 cell의 속성으로 해결할 수 있는 부분이니 사용해보세요!
(cellForRowAt 에서 호출하시면 됩니다.)

2023-05-16 06:19 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/PlayListTableViewCell.swift
> +            let view = UIView(frame: CGRect(x: 0, y: 0, width: 0, height: 0))
@DONOTINTO 
다른 코드에서 나온 side-effect 였을 수 있습니다ㅎㅎ 
잘 작동한다니 다행이네요!

2023-05-16 06:20 UTC, keenkim1202 requested changes
한 가지만 더 수정해주시면 될 것 같습니다! 코멘트 남겨두었습니다 @DONOTINTO

2023-05-16 14:57 UTC, DONOTINTO commented on Login_SpotifyUI/Login_SpotifyUI/Controller/PlayListTableViewCell.swift
> +    override func setHighlighted(_ highlighted: Bool, animated: Bool) {
@keenkim1202 수정완료했습니다!

2023-05-17 05:29 UTC, keenkim1202 approved these changes
수고하셨습니다~!

2023-05-17 05:29 UTC, merged