JY-110 : 회원탈퇴 기능을 구현한다
DONOTINTO/Login_SpotifyUI pull request #45
Opened 2023-05-13 05:34 UTC by DONOTINTO

- 카드번호 : [JY-110](https://keentutoring.atlassian.net/browse/JY-110)

2023-05-13 16:02 UTC, keenkim1202 requested changes

2023-05-13 16:02 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +        guard let heightForRow = self.heightForRow else { return 0 }
`heightForRow`가 `nil`일 경우 0을 사용할 것이라면, `Optional` 타입일 필요가 있을까요?

2023-05-13 16:02 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/LoginViewController.swift
> +                self.loginData?.loginUpdate(item: register, loginStatus: true)
`Optional`값은 안전하게 가져와주세요~

2023-05-16 06:25 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +    var heightForRow: CGFloat?
@DONOTINTO 
그렇다면 원래 cell의 높이값은 CGFloat 타입을 사용하도록 설계되어있는 것이므로, (Int 타입으로 형변환해서 사용하지 않고) CGFloat 타입을 쭉 사용하면됩니다.
updateUI(height:) 의 인자를 Int가 아닌 CGFloat 타입을 받아 사용하시면 문제가 해결될 것 같습니다~!

숫자의 범위가 CGFloat > Int 인데, 우리가 임의로 Int로 범위를 줄일 필요는 없을 듯 합니다!

2023-05-16 06:25 UTC, keenkim1202 requested changes
@DONOTINTO 
하나 추가 수정사항이 있습니다. 확인&반영 후 re-request 해주세요~!

2023-05-16 15:02 UTC, DONOTINTO commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +    var heightForRow: CGFloat?
@keenkim1202 수정완료했습니다
updateUI에서 Int로 변경한 이유는 rowHeight에 count(Int 타입)을 곱해야 하기 때문인데, rowHeight를 Int로 바꾸는 것과 count를 CGFloat으로 바꾸는것과 차이가 있는 걸까요?

2023-05-17 05:33 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +    var heightForRow: CGFloat?
@DONOTINTO 구두로 설명 완료되었으므로 resolve 하겠습니다~

2023-05-17 05:33 UTC, keenkim1202 approved these changes

2023-05-17 05:33 UTC, merged