JY-86
DONOTINTO/Login_SpotifyUI pull request #48
Opened 2023-06-04 10:00 UTC by DONOTINTO

- 카드번호 : [JY-86](https://keentutoring.atlassian.net/browse/JY-86)

2023-06-05 07:20 UTC, keenkim1202 approved these changes
@DONOTINTO 
선택적인 수정사항 밖에 없습니다. 수고하셨습니다~

1 )
원하는 경우 수정 해주세요~! 수정하지 않을 경우 코멘트 남겨주시면 머지처리하겠습니다.

2 )
Scheme을 건들이는 과정에서 문제가 발생한 듯합니다.
제가 JY-86 브랜치를 pull 하자마자 실행하면 No Scheme이라고 뜹니다. 
일단 임의로 새로운 scheme을 생성하여 테스트하였습니다.
Scheme을 변경하신 경우, 변경사항을 포함하여 PR을 올려주세요~!

<img width="1000" src="https://github.com/DONOTINTO/Login_SpotifyUI/assets/59866819/d5ea2701-cdb6-43b5-98c5-743578531a68">

2023-06-05 07:20 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +        guard let realm = self.realm else { return }
(참고: 지금 코드 순서도 전혀 문제 없습니다!)

저라면 88, 89번 줄 guard문 순서를 바꿀 것 같습니다🙂
결국 realm이 존재하지 않는다면 add 행위가 일어날 수가 없기 때문에 가장 상단에 두고 먼저 체크해야한다고 여겨서 입니다.

2023-06-05 07:20 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +        let newMusic = Music(identification: register.identification, title: "\(randomCount)", artist: "test-artist")
(선택사항)
`identification` 의 내이밍이 너무 긴 것 같습니다.
`id`로 축약하면 어떨까요?

2023-06-05 07:20 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/EntryViewController.swift
> +        let signUpVC: SignUpViewController = {
아래의 다른 코드들에는 위에 추천드린 코드와 같은 형식으로 선언되어있는데, 
`signUpButtonClicked()`, `loginButtonClicked()` 에서만 이렇게 선언되어있어서 코멘트 남깁니다.

2023-06-05 07:20 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +        guard let realm = self.realm else { return }
(선택)
여기도 마찬가지로 저라면 realm을 가장 먼저 선언할 것 같습니다~!
어차피 realm이 nil이라면 register를 체크하고 난 뒤 걸러지겠지만, 가장 먼저 체크해야할 사항이라고 보기 때문입니다.

2023-06-06 10:50 UTC, DONOTINTO commented
@keenkim1202 수정 완료했습니다!

2023-06-06 15:52 UTC, keenkim1202 requested changes

2023-06-06 15:52 UTC, keenkim1202 commented on Login_SpotifyUI/Login_SpotifyUI/Controller/HomeViewController.swift
> +        filteredData = register.getPlayListArray()
```suggestion
        filteredData = register.getPlayList()
```

(참고)
@DONOTINTO 

- UI에 사용되는 객체(UIImage, UITextField...)를 제외하고는 함수 혹은 변수명에 가능하면 타입 이름 자체(Int, Array, String...)을 명시하는 것은 지양하는 것이 좋습니다.
    - [Swift 공식 네이밍 컨벤션 참고](https://www.swift.org/documentation/api-design-guidelines/#naming)
- 우리는 play"List" 에서 "List" 라는 단어를 통해 `목록` 즉, `배열(Array)`임을 이미 명시해주었습니다.
- 거기에 `Array`를 뒤에 붙인다면 배열임을 나타내는 단어를 중복해서 사용하게 된 것입니다.
   - 의미가 중복되는 단어를 여러 번 사용하여 불필요하게 네이밍을 길게 늘릴 필요 없습니다.

- 알고리즘 문제에는 특정 변수명에 의미를 부여할 필요가 없기 떄문에 네이밍에 `testArray`, `testString` 과 같이 작성하곤 합니다.

2023-06-06 15:54 UTC, keenkim1202 commented
@DONOTINTO 
`(선택)` 으로 표기된 코멘트의 경우, 
반영하지 않기로 결정하셨다면 **코멘트를 확인했는지 여부를** 제가 알 수 있도록 👍🏻 표시 부탁드려요!

2023-06-09 12:19 UTC, merged